# Generated by Django 2.0.7 on 2018-08-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
