# Generated by Django 2.0.7 on 2018-07-29 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.URLField(blank=True)),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('contact', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, db_index=True)),
                ('github', models.URLField(blank=True, db_index=True)),
                ('total_stars', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
