# Generated by Django 2.0.7 on 2018-08-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20180729_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, default='https://static.productionready.io/images/smiley-cyrus.jpg'),
        ),
    ]
