# Generated by Django 2.0.7 on 2018-08-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20180802_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_stars',
            field=models.BigIntegerField(default='0'),
        ),
    ]
