# Generated by Django 2.0.7 on 2018-08-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20180802_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website',
            field=models.TextField(blank=True, db_index=True),
        ),
    ]
