# Generated by Django 2.0.7 on 2018-08-02 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiddle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('stars', models.BigIntegerField()),
                ('HTMLelement', models.CharField(blank=True, max_length=255)),
                ('HTMLCode', models.TextField(blank=True)),
                ('CSSCode', models.TextField(blank=True)),
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('votes', models.BigIntegerField()),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='fiddle_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
